services:
  ui_gateway:
    build: null                 # ← anula la sección build del base
    image: node:18-alpine
    command: sh -c "apk add --no-cache npm && npm install && npm run dev -- --host"
    working_dir: /app
    volumes:
      - ./ui_web:/app           # monta el código
    ports:
      - "5173:5173"             # hot-reload
    environment:
      - VITE_ROSBRIDGE_URL=ws://localhost:9090
      - VITE_API_URL=http://localhost:5000
    networks:
      - ros_net

  api:
    build: null
    image: python:3.11-slim
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    working_dir: /app
    volumes:
      - ./api:/app
      - ./maps:/maps
    networks:
      - ros_net
